### ISSUE TITLE
Lock rotation and calculate bounding box

### ISSUE THREAD

**Issue by Razi91** [gvellut/FreehandRasterGeoreferencer#27]
it would be very useful, if there would be a possibility to lock rotation, but even better if in QGIS project were saved bounding box for selected projection. It would be very helpful in generating GeoTIFF for geoserver.

**Comment by gvellut** [comment]
Thank you for your feedback. I am not sure I understand the bit about generating GeoTIFF for geoserver. Can you tell me more about your use case? Note that, even though the bounding box is not saved in the .QGS file, it is possible to compute it using the parameters that are saved (center, scale, rotation) + the image size.

**Comment by Razi91** [comment]
I have over 150 mapped tiles with your plugin and I'd like to serve them through WMS on GeoServer. I managed to read .qgs files to get those data, but calculations are not precise: there is a big offset and I don't know how to scale if properly, just `xCenter - xCenter * xScale` doesn't help, I had to find a value like 1350 that was valid for this latitude.

**Comment by Dkrav-UA** [comment]
listgeo -tfw file.tif
This will extract tfw files from GeoTiff.
If you need tfw in another projection, then you need to reproject images to desired projection.

**Comment by gvellut** [comment]
You could use the "Export raster with world file" command (you will need to check the "Put rotation in world file” option). This will generate a TFW (and will also export an image, but it should be identical to the original). If you don't want to do it manually, I guess you could script the call to that command for all the georeferenced layers in your project. Or, since you have already extracted the parameters from the .QGS, you could also do the calculation yourself based on the existing code in the [freehandrastergeoreferencer_commands.py](https://github.com/gvellut/FreehandRasterGeoreferencer/blob/master/freehandrastergeoreferencer_commands.py) file:

```python
radRotation = rotation * math.pi / 180
a = xScale * math.cos(radRotation)
b = -yScale * math.sin(radRotation)
d = xScale * -math.sin(radRotation)
e = -yScale * math.cos(radRotation)
c = xCenter - (a * (imageWidth - 1) / 2 +
          b * (imageHeight - 1) / 2)
f = yCenter - (d * (imageWidth - 1) / 2 +
          e * (imageHeight - 1) / 2)
```

And you can create the .TFW by writing the values of "a b d e c f" each on a different line.

**Comment by gvellut** [comment]
@Razi91 Closing for now. Reopen if your issue has not bee solved.
